# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20180407_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edito',
            field=models.TextField(blank=True, null=True, verbose_name='edito'),
        ),
    ]
