# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newsletter_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('SPOTLIGHT', 'SPOTLIGHT'), ('FOCUS', 'FOCUS'), ('VIDEO', 'VIDEOS'), ('DIARY', 'DIARY')], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
