# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newsletter_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.CharField(choices=[('100%', '100%'), ('50%', '50%'), ('33%', '33%')], default='100%', max_length=4, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='auth.Group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsletter.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='newsletter.Category', verbose_name='Categories'),
        ),
    ]
