# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('newsletter', '0007_article_column'), ('newsletter', '0008_auto_20181130_1349'), ('newsletter', '0009_auto_20181205_1442')]

    dependencies = [
        ('newsletter', '0006_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.CharField(choices=[('100%', '100%'), ('50%', '50%'), ('33%', '33%')], default='100%', max_length=4, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('ACTUALITES', 'ACTUALITÉS'), ('UNIVERSITE ET VOUS', 'L’UNIVERSITÉ ET VOUS'), ('FOCUS', 'FOCUS'), ('VIDEO', 'VIDEO'), ('AGENDA', 'AGENDA')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
